// Generated by CoffeeScript 1.3.3
(function() {

  exports.init = function(app) {
    app.get('/', require('./controllers/home').index);
    return app.get('/sync', require('./controllers/home').sync);
  };

}).call(this);
